from typing import List, Dict, Optional
from pydantic import BaseModel, Field

# --- 1. Context ---
class CorporateContext(BaseModel):
    primary_company: str
    parent_company_or_group: Optional[str] = None
    brand_consistency_notes: str

# --- 2. Domain & Financials ---
class DomainShare(BaseModel):
    domain: str = Field(..., description="Free text domain name (e.g. 'Renewable Energy').")
    percentage: int
    justification: str

class FinancialEstimates(BaseModel):
    suggested_price_factor: float
    explanation: str
    component_impact_breakdown: List[str]
    weighted_base_coefficient: float
    difficulty_multiplier: float
    dtp_surcharge: bool

# --- 3. Profile ---
class DocumentProfile(BaseModel):
    document_type: str
    target_audience_groups: List[str]
    reading_level: str
    content_components: List[str]

# --- 4. Components ---
class ComponentAnalysis(BaseModel):
    text_volume_summary: str
    visual_elements_summary: str
    data_tables_summary: str
    ocr_requirements: str
    formatting_impact_score: int

# --- 5. Measurements & Protocols (FIXED EMPTY SECTION) ---
class MeasurementRules(BaseModel):
    decimal_format_rule: str = Field(..., description="e.g. 'Convert German comma to English dot'.")
    unit_conversion_rule: str = Field(..., description="e.g. 'Keep kWp as is, convert Hectares to Acres'.")
    critical_measurements_list: List[str] = Field(..., description="List specific numbers found (e.g. '8.821,8').")

class DifficultyDrivers(BaseModel):
    terminology_count: int
    technical_density_score: str
    regulatory_constraints: str
    formatting_complexity: Optional[str] = None

class Difficulty(BaseModel):
    overall_difficulty_level: int
    drivers: DifficultyDrivers

# --- 6. Resources ---
class LinguistProfile(BaseModel):
    headline_profile: str
    education_requirement: str
    min_years_experience: int
    seniority_level: str
    required_experience: List[str]
    tool_recommendations: List[str]

# --- 7. Terminology ---
class TerminologyResources(BaseModel):
    glossary_status: str
    categorized_terms: Dict[str, List[str]] # Prompt will ask for 20+

# --- 8. Strategy (NEW FEATURE) ---
class LocalizationStrategy(BaseModel):
    cultural_adaptation_notes: str = Field(..., description="How to handle cultural nuances.")
    geographic_handling: str = Field(..., description="How to handle locations (e.g. keep original or transliterate).")
    tone_and_style_guide: str

# --- 9. Risks ---
class Risk(BaseModel):
    name: str
    category: str
    description: str
    evidence_from_text: str
    mitigation: str

# --- 10. Workflow ---
class DetailedWorkflow(BaseModel):
    pre_processing: List[str]
    translation_process: Optional[str] = None
    qa_and_review: List[str]
    post_processing: List[str]

class PMNotes(BaseModel):
    executive_summary: str
    special_considerations: List[str]
    questions_for_client: List[str]

# --- MAIN MODEL ---
class DocumentAnalysis(BaseModel):
    document_names: List[str]
    original_file_types: List[str] = []
    analysis_date: str
    analyzed_by: str = "AI Enterprise Analyst"
    
    high_level_description: str
    corporate_context: CorporateContext
    entities_detected: List[str]
    
    component_analysis: ComponentAnalysis
    measurement_rules: MeasurementRules # Replaced list with structured rules
    
    domain_breakdown: List[DomainShare]
    doc_profile: DocumentProfile
    
    localization_strategy: LocalizationStrategy # NEW
    
    source_language_variant: str
    register_formality_level: str
    difficulty_complexity: Difficulty
    recommended_resources: LinguistProfile
    terminology_and_resources: TerminologyResources
    risks_and_mitigations: List[Risk]
    workflow_recommendations: DetailedWorkflow
    financial_metrics: Optional[FinancialEstimates] = None
    pm_notes: PMNotes
    
    footnote: str = "Generated by AI Enterprise System."